serverPort: http://b652-2405-4802-7014-8d10-381f-c355-70d8-da76.ngrok.io/
#serverPort: http://192.168.1.44:8080

uploadPath: D:/upload
domainUploadPath: http://localhost:8080/authentication-service/files
spring:
  application:
    name: authentication-service
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    url: jdbc:postgresql://localhost:5432/authentication
    username: postgres
    password: arettes123
  #    password: 123456789
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  resources:
    static-locations: file:${uploadPath}
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
  main:
    allow-bean-Definition-overriding: true
server:
  port: 8082
  tomcat:
    uri-encoding: UTF-8
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
#security:
#  oauth2:
#    client:
#      client-id: authentication-client
#      client-secret: 123123123
swagger:
  authen:
    #    url: http://103.195.236.218:8080/authentication-service
    url: ${serverPort}/authentication-service
