server:
  port: 8080
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
spring:
  main:
    web-application-type: reactive
  application:
    name: gateway-service
  cloud:
    discovery:
      enabled: true
    gateway:
      #      default-filters:
      #        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      #      globalcors:
      #        corsConfigurations:
      #          '[/**]':
      #            allowedOrigins: "*"
      #            allowedMethods:
      #              - GET
      #              - POST
      #              - DELETE
      #              - PUT
      #              - OPTIONS
      #            allowedHeaders: "*"
      routes:
        - id: authentication-service
          uri: lb://authentication-service
          predicates:
            - Path=/authentication-service/**
        - id: coffee-service
          uri: lb://coffee-service
          predicates:
            - Path=/coffee-service/**
      discovery:
        locator:
          lower-case-service-id: true
          enabled: true
#  http:
#    encoding:
#      charset: UTF-8
#      enabled: true
#      force: true
#
#  servlet:
#    multipart:
#      enabled: true
#      max-file-size: -1
#      max-request-size: -1

management:
  endpoint:
    gateway:
      enabled: true
  endpoints:
    web:
      exposure:
        include: gateway
logging:
  file: gateway.log
  level:
    root: INFO
    org.springframework: INFO

security:
  oauth2:
    client:
      client-id: coffee-client
      client-secret: 123123123
